{% set version = "1.44" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-verification
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/verification_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/verification/verification_{{ version }}.tar.gz
  sha256: 140ea006b98da0e9ac64231ff8a50d0aa878d3a7ad65c95d2fc548118506ab24

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-circstats
    - r-mass
    - r-boot
    - r-dtw
    - r-fields
  run:
    - r-base
    - r-circstats
    - r-mass
    - r-boot
    - r-dtw
    - r-fields

test:
  commands:
    - $R -e "library('verification')"           # [not win]
    - "\"%R%\" -e \"library('verification')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=verification
  license: GPL (>= 2)
  summary: Utilities for verifying discrete, continuous and probabilistic forecasts, and forecasts expressed as parametric distributions are included.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
