travis:
  secure:
    BINSTAR_TOKEN: DjyTLVCxybu0//lssWGlUI+7Zo6ZzgjXZZQpumBn5Jmx/EUTkCQLXpRqRTaZeb4hYW6XbhdWGRZV+JCeDZLDkfScTTbYxAemCNYp8k6PNiZydIBvXhSisG3PNPaq+pue6Mv3U3jI0cr/zjEqaytj4+SXqIvwxH1kbUZfBNf5WvpZm3OzvM4uPAkrRCRFI0aVpnd/O/0evjH/lUH8oBSCB2d8rF0+NL4EXl5XTQ1MofHB2H9IIyxj6wM2Sj363DuY6nGTFMUQ4cIGNw9gT3ZaS452g0rUTXOHNZJPmWZiKHZK+UUGlN6aplJqPwPHgRgsoNkH/YIlD4+H/2j2yfzBM2vSdVWeZx9SXLFo2jTL1drNk7nmzsHYP4HzdmHhuZtaPl7hf0phDipbWBdtvG1RzPH11VQbWIrvluZVG0KifiONX7UPdU7O9NQSlkM/SsF4TdmCeo5L+xuzrCAChUxoudUFIxVJkA9PoypUmS0jRupzNIfGpMnEXyM3BajOwDoSLHCNjn8ktcn0nIy6RaPT3CWPmmC+T6raI8vl8Pccq1UcoqvFs7a+6dl6uEKuxnMW7ZIFAeJTyYXInGhB+5QockJQonZQUAifxRnVdHvDun21Nein0Q1vONSmudPRZ1coDfy3KWc4N3c9XusrbNiKfaDJGzEDp9/uBTxVOgVMoVg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
